CREATE DATABASE doingsdone DEFAULT CHARACTER SET UTF8 DEFAULT COLLATE UTF8_GENERAL_CI;
USE doingsdone;
CREATE TABLE users(
	id INT AUTO_INCREMENT PRIMARY KEY,
	registration TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	email VARCHAR(128) NOT NULL UNIQUE,
	name CHAR(255) NOT NULL,
	password CHAR(64)
);
CREATE UNIQUE INDEX email ON users(email);
CREATE INDEX name ON users(name);
CREATE TABLE projects (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name CHAR(255) NOT NULL,
	FOREIGN KEY (id) REFERENCES users(id)
);
CREATE INDEX name ON projects(name);
CREATE TABLE tasks(
	id INT AUTO_INCREMENT PRIMARY KEY,
	create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	state TINYINT(1) NOT NULL,
	name CHAR(255) NOT NULL,
	file BLOB,
	expiration DATE,
	FOREIGN KEY (id) REFERENCES users(id),
	FOREIGN KEY (id) REFERENCES projects(id)
);
CREATE INDEX expiration ON tasks(expiration);